# Generated by Django 4.2.7 on 2023-12-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitepages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fram',
            field=models.CharField(choices=[('0', 'django'), ('1', 'flask'), ('2', 'featured')], max_length=50),
        ),
    ]
